#import <Foundation/Foundation.h>
#import "USAdditions.h"
#import <libxml/tree.h>
#import "USGlobals.h"
@class ns8_ArrayOfRole;
@class ns8_Role;
@class ns8_ArrayOfPermission;
@class ns8_Permission;
@class ns8_PermissionCategory;
